# Generated by Django 2.2 on 2019-04-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('target', models.CharField(default='', max_length=200)),
                ('workout_time', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('exercise_target', models.CharField(default='', max_length=200)),
                ('time', models.CharField(default='', max_length=200)),
                ('video_url', models.CharField(default='', max_length=600)),
                ('description', models.TextField(default='', max_length=1000)),
                ('benefits', models.TextField(default='', max_length=1000)),
                ('workout', models.ForeignKey(on_delete='CASCADE', related_name='exercises', to='brio_app.Workout')),
            ],
        ),
    ]
