# Generated by Django 2.2 on 2019-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brio_app', '0002_ingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='directions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
