# Generated by Django 2.2 on 2019-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brio_app', '0004_remove_ingredient_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='benefits',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
